### ISSUE TITLE
Implement the entities

### ISSUE THREAD

**Issue by awesominat** [awesominat/stonks#1]
implement the necessary enterprise business rules by creating the following entities,

enum OrderType
	BUY,
	SELL,
	TOPUP

Transaction:
	Public int amountBought
	Public int identifier
	Public OrderType orderType
	Public LocalDate timeBought
	Public double priceBought
	Public Double priceSold

PricePoint:
	Public LocalDate timeStamp
	Public Double price

Stock:
	Public Double lastSeenPrice
	Public List<PricePoint> priceHistory
	Public String fullName
	Public String ticker

TransactionHistory:
	Public Stock stock
	Public List<Transaction> transactions

User:
	private TransactionHistory[] portfolio
	Private String username
	Private String password
	private Hashmap<String, TransactionHistory> history
	Private Double balance = 10000.0

any issues that come throughout the project might warrant entities to change to fit the changing specification. but for now, these entities work fine

**Comment by rickypramanick** [comment]
luh calm workflow
