### ISSUE TITLE
Fix bug with sell not updating with recently bought stocks and change behaviour of sell stocks button

### ISSUE THREAD

**Issue by gursi26** [awesominat/stonks#116]
Fix/implement the following in the SellView:
1. Occasionally, the SellView does not update with a recently bought stock, likely due to dashboardController never being called, so dashboardstate is never updated. Fix this by adding a dashboardController.execute call in the DashboardView property changed method.
2. Display a success popup when sold stocks successfully instead of going back to dashboard screen.

**Comment by awesominat** [comment]
@gursi26 is this fixed? as it isn't linked by any PR

**Comment by gursi26** [comment]
Fixed
