### ISSUE TITLE
Money Display modifications

### ISSUE THREAD

**Issue by quiz3** [awesominat/stonks#151]
There are several ways in which we need to change the way we are rendering quantities of money.

- First and foremost, we are not using the dollar sign ($), which is critical, as otherwise the numbers do not mean anything.
- Secondly, we need to round every dollar amount to two decimal places or zero decimal places (at least for the purposes of rendering them on-screen), since dollars are not measured in any other denomination.

**Comment by gursi26** [comment]
Done on all screens
