### ISSUE TITLE
add get company news use case, interface adapters, and view

### ISSUE THREAD

**Issue by awesominat** [awesominat/stonks#30]
in a list format, allow the user to get a certain company's information (maybe cap it at 5 stories sorted by newest for now)

**Comment by quiz3** [comment]
I believe this is all done

**Comment by quiz3** [comment]
I just realized the reason this was still open was cuz I hadn't done the interface adapters or view yet

**Comment by quiz3** [comment]
The only thing remaining now for the GetNews use case to be complete is the `GetNewsView` in the `view` package. It has been started but there still remains some work to do.
