### ISSUE TITLE
add Builder to CompanyInformation

### ISSUE THREAD

**Issue by awesominat** [awesominat/stonks#33]
a possible design pattern we could implement is to build the CompanyInformation instead of passing all the arguments in at once.

This will allow us to input as many arguments as we want without creating at most 6 constructors.

However, now that our code has been developed further, I see that we don't have a case where we'd pass in less than 6 arguments.

As such, I am willing to close this issue.

**Comment by quiz3** [comment]
@awesominat can you please provide a description for this Issue?

**Comment by awesominat** [comment]
I will close this issue as it is not necessary as described in the description
