### ISSUE TITLE
clean up dashboard use case

### ISSUE THREAD

**Issue by awesominat** [awesominat/stonks#64]
see #63 

> currently the file needs methods extracted so it looks cleaner as it doesn't look the best right now, but this is sufficient for purposes of getting the program working

**Comment by quiz3** [comment]
@awesominat can this issue be deleted now?

**Comment by awesominat** [comment]
no, the pr mentioned talks about how the dashboard use case can be refactored so that it can be cleaner

**Comment by quiz3** [comment]
> no, the pr mentioned talks about how the dashboard use case can be refactored so that it can be cleaner

What about now, is it still messy?

**Comment by gursi26** [comment]
This was fixed in #148

**Comment by awesominat** [comment]
I think it is better than before
