### ISSUE TITLE
Creating use case factories for all use cases

### ISSUE THREAD

**Issue by gursi26** [awesominat/stonks#90]
As indicated in the title, creating use case factories that initialize multiple objects like the Controller, Interactor, State, View Model, Presenter and View will make for easier and quicker testing and a simpler Main.java file when the app is completed.

**Comment by gursi26** [comment]
Not closed yet, other use case factories still need to be implemented

**Comment by awesominat** [comment]
I have checked and we now have as many use case factories as use cases
